# Generated by Django 4.2.1 on 2023-05-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.BooleanField(default=False)),
                ('date', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=255)),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persent', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('user_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='app.usermodel')),
            ],
        ),
    ]
