# Generated by Django 4.2.1 on 2023-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
